### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by ApplePieGiraffe** [funnyducksup/master#1]
Just wanted to say hi. :)

**Comment by funnyducksup** [comment]
Hi, how is it going? :)

**Comment by ApplePieGiraffe** [comment]
I'm doing well. :)

Do you like to code?

**Comment by funnyducksup** [comment]
Of course I like, but think my education is slowly :D Just a noob haha 
What about you? First place on FrontendMentor is cool result!!!

**Comment by funnyducksup** [comment]
Do you have discord or another way for connection? :)

**Comment by ApplePieGiraffe** [comment]
Oh, hey! Sorry for the late reply. I like to code, too, of course! We can chat more on Slack if you'd like. Frontend Mentor has an awesome Slack community that you can join and you can find me there! 👍
